export type AppDataBundle = { schemaVersion: 1; exportedAt: string; data: Record<string, unknown> };
export type BrowserAppDataBackup = Map<string, string | null>;
const PALOS_KEYS = [
  "ai-learning-os.workspaces", "ai-learning-os.conversations", "ai-learning-os.sources", "ai-learning-os.current-source", "ai-learning-os.messages", "ai-learning-os.rounds", "ai-learning-os.proposals", "ai-learning-os.current-proposal", "ai-learning-os.knowledge-cards", "ai-learning-os.assets", "ai-learning-os.tasks", "ai-learning-os.tags", "ai-learning-os.analyzer-runs", "ai-learning-os.conversation-versions", "ai-learning-os.recipes", "ai-learning-os.feedback", "ai-learning-os.app-event-log", "ai-learning-os.provider-configurations", "ai-learning-os.analyzer-prompt-templates", "ai-learning-os.current-provider",
] as const;
export class BrowserAppDataStorage {
  exportData(keys: readonly string[] = PALOS_KEYS): AppDataBundle { const data: Record<string, unknown> = {}; keys.forEach((key) => { const raw = window.localStorage.getItem(key); if (raw !== null) { try { data[key] = JSON.parse(raw); } catch { data[key] = raw; } } }); return { schemaVersion: 1, exportedAt: new Date().toISOString(), data }; }
  preview(text: string) { const bundle = JSON.parse(text) as AppDataBundle; if (bundle?.schemaVersion !== 1 || !bundle.data || typeof bundle.data !== "object") throw new Error("Unsupported app data bundle."); const keys = Object.keys(bundle.data); if (keys.some((key) => !PALOS_KEYS.includes(key as typeof PALOS_KEYS[number]))) throw new Error("Bundle contains unknown keys."); return { bundle, keys, counts: Object.fromEntries(keys.map((key) => [key, Array.isArray(bundle.data[key]) ? bundle.data[key].length : 1])) }; }
  importData(bundle: AppDataBundle, selectedKeys: string[]) { const allowed = selectedKeys.filter((key) => PALOS_KEYS.includes(key as typeof PALOS_KEYS[number]) && key in bundle.data); const previous = this.createBackup(allowed); try { allowed.forEach((key) => window.localStorage.setItem(key, JSON.stringify(bundle.data[key]))); } catch (error) { this.restoreBackup(previous); throw error; } return allowed.length; }
  createBackup(selectedKeys: string[]): BrowserAppDataBackup { const allowed = selectedKeys.filter((key) => PALOS_KEYS.includes(key as typeof PALOS_KEYS[number])); return new Map(allowed.map((key) => [key, window.localStorage.getItem(key)])); }
  restoreBackup(backup: BrowserAppDataBackup): void { backup.forEach((value, key) => value === null ? window.localStorage.removeItem(key) : window.localStorage.setItem(key, value)); }
  verifyBackup(backup: BrowserAppDataBackup): void { backup.forEach((value, key) => { if (window.localStorage.getItem(key) !== value) throw new Error(`LocalStorage backup verification mismatch for ${key}.`); }); }
  verifyData(bundle: AppDataBundle, selectedKeys: string[]): number { const allowed = selectedKeys.filter((key) => PALOS_KEYS.includes(key as typeof PALOS_KEYS[number]) && key in bundle.data); for (const key of allowed) { const raw = window.localStorage.getItem(key); if (raw === null) throw new Error(`LocalStorage verification failed for ${key}.`); let actual: unknown; try { actual = JSON.parse(raw); } catch { actual = raw; } if (JSON.stringify(actual) !== JSON.stringify(bundle.data[key])) throw new Error(`LocalStorage verification mismatch for ${key}.`); } return allowed.length; }
}
